workflows:
  android-build:
    name: Check Repo Contents
    max_build_duration: 10
    instance_type: mac_mini_m1
    scripts:
      - name: List files
        script: |
          echo "=== Danh sách file trong Repo ==="
          find . -maxdepth 3 -not -path '*/.*'
